services:
  devflowfix:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.dev
    container_name: devflowfix-backend
    restrat: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres+psycopg2://postgres:postgres@postgres:5432/vector_db
      - ENVIRONMENt=development
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres-vector
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries=vector
      -c max_connections=200

volumes:
  pgdata:
